### ISSUE TITLE
How can I manually expire the cache for a particular module that I have just updated?

### ISSUE THREAD

**Issue by runvnc** [mixu/npm_lazy#20]
Say I just published a module update to the register and I want to do a final verification that it works.  So I don't want to wait the normal cache expiration time, I want to download the latest version.

Is there a flag or command or something so that I can purge the lazy cache of that particular module so it will be redownloaded from the registry?

**Comment by gustavohenke** [comment]
@mixu, is this still the only way to do it?
We are using npm_lazy as the registry for our CI builds, and I don't have SSH access to that server, only the DevOps guys.

**Comment by mixu** [comment]
you can also set `cacheAge` to 0 (the default), that should force a refresh 

https://github.com/mixu/npm_lazy/blob/42f16f3b096cc737f936751fcedaf7419518c35a/lib/resource.js#L92
