### ISSUE TITLE
Add command-line support for configuration options

### ISSUE THREAD

**Issue by langri-sha** [mixu/npm_lazy#47]
It would be great if configuration could also be managed from the command-line, for cases where it is impractical or impossible to author/manage several configuration files.

**Comment by brunobatista** [comment]
:+1:

**Comment by mixu** [comment]
Could you give a more concrete example of how this would work? What does managing configuration mean here? I'm trying to understand why switching between multiple config files is impractical.

**Comment by langri-sha** [comment]
I've been running instances for personal use for quite some time--the typical setup with the server and NPM client running on the same host, based on the provided defaults. Now that I find myself bringing it to various distinct environments, with the client and server always running on separate hosts in dynamic computer networks, I've found myself dealing with configuration creep which stems from the assumption that the configuration module, and the server's environment for that matter, are static, known well in advance and need only be authored/specified once.

The issues I've encountered could have easily been resolved if I was permitted to use string interpolation to provide dynamic facts about my infrastructure, an approach which users can immediately utilize with their platform providers, schedulers or provisioners, e.g.:

```
bin/npm_lazy -p $NPMLAZY_PORT -e http://$NPMLAZY_HOSTNAME:$NPMLAZY_PORT
```

In order to make this work, I guess it would be best to recycle parts of `npm`'s tried-and-true approach, which applied to `npm_lazy` would probably entail:

- making `npm_lazy/config.js` the authoritative source for defaults (and their documentation)
- updating the defaults with the exported object from custom configuration modules, if provided via `-c`, `--config`, making it possible to provide only a subset of default overrides
- overriding the resulting config with any command-line options provided

**Comment by contra** [comment]
+1 this will make install as easy as `npm install npm_lazy -g`

**Comment by davidlanger** [comment]
Yep, I like this idea as well, especially as I only change the port. One would be up and running way faster this way

**Comment by albertosouza** [comment]
+1 for: npm_lazy -p $NPMLAZY_PORT -e http://$NPMLAZY_HOSTNAME:$NPMLAZY_PORT

**Comment by mixu** [comment]
thanks @albertosouza - published as `v.1.9.0`!
