### ISSUE TITLE
Make config overrideable with command line options

### ISSUE THREAD

**Issue by Tzrlk** [mixu/npm_lazy#54]
At the moment, the only way of changing the port that it runs on is by manually altering the config.js file. It's simple enough to look for an environment variable, and slightly harder to look for a command line option.

**Comment by langri-sha** [comment]
We have a discussion open on #47 if you'd like to pitch in with your concerns and ideas.

**Comment by Tzrlk** [comment]
Ah, missed that one. Good catch.
