### ISSUE TITLE
Private Modules: public dependencies are not loaded through proxy

### ISSUE THREAD

**Issue by ryan-kimber** [mixu/npm_lazy#60]
When using NPM Lazy, I've noticed that, when I run 'npm install' in one of my private module projects, none of the modules are retrieved through NPM lazy - they all come directly from npmjs.org.

If I try to force npm to use NPM Lazy for my private modules (by adding @name:registry=http://localhost:8080/ to .npmrc), NPM Lazy responds with a 404 for all @name modules.

Is this a bug, a missing feature, or is there some configuration for private modules that needs to be documented?

**Comment by CL0SeY** [comment]
It's a side-effect/bug from quickly implementing the private modules feature.

We will need to ensure we do a find/replace on the metadata for these kind of resources instead of just simply proxying through to npm.

**Comment by mixu** [comment]
I just added support for scoped modules in `v1.10.0`. Give it a try and let me know if you run into any issues!

**Comment by ryan-kimber** [comment]
Does this handle authentication for the private modules as well? I couldn't find documentation on the feature.

**Comment by mixu** [comment]
ah I think it'll only work for scoped modules - reopening. I should just buy a npm account to do more testing

**Comment by jsierles** [comment]
I can confirm that it doesn't work with an authToken setup in .npmrc. Would love to help and add this. What might be the best approach? Add a config option to npm_lazy to specify the token?
