### ISSUE TITLE
First time install is significantly slower than npm direct

### ISSUE THREAD

**Issue by aaronjensen** [mixu/npm_lazy#68]
I'm not sure if I'm doing something wrong or not, but the first time I install a set of packages for a project through npm_lazy it takes significantly longer. On the order of 3-10x longer.

**Comment by mixu** [comment]
I'm guessing that it's related to fetching and caching the modules the first time would be happy to get a benchmark so this could be measured and improved systematically!

**Comment by aaronjensen** [comment]
how would you like me to benchmark it? fwiw, I'm doing this with docker, both the npm install and the npm_lazy are running in two separate containers

**Comment by aaronjensen** [comment]
I think I just needed to give my containers more cpu-quota. Upon doing so things seemed to be faster, at least with npm 2. I'll close this out and reopen if I run into another issue. Thanks!
