### ISSUE TITLE
Support for caching npm scoped packages (e.g @angular)

### ISSUE THREAD

**Issue by reda-alaoui** [mixu/npm_lazy#69]
Hello,

This issue is a clone of #64.
Since we had no answer on #64 and we can't reopen it, I tought that creating a new one would result in a better visibility in the default issue filter.

It seems that `npm_lazy` is still unable to cache npm scoped packages.

**Comment by finico** [comment]
@reda-alaoui It looks like it's working

`> npm --registry http://localhost:8080/ install @angular/common@2.0.2 @angular/core@2.0.2 @angular/forms@2.0.2`

```
test@1.0.0 ~/src/test
├── @angular/common@2.0.2  extraneous
├── @angular/core@2.0.2  extraneous
├── @angular/forms@2.0.2  extraneous
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@^0.6.21`

```

`> rm -r node_modules`
disable wi-fi
`> npm --registry http://localhost:8080/ install @angular/common@2.0.2 @angular/core@2.0.2 @angular/forms@2.0.2`
`> npm ls`

```
test@1.0.0 ~/src/test
├── @angular/common@2.0.2 extraneous
├── @angular/core@2.0.2 extraneous
├── @angular/forms@2.0.2 extraneous
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@^0.6.21
```

**Comment by mike42** [comment]
This does work.

I was able to repeat the steps shown by @finico with no issues, on `npm_lazy` 1.13.0, `npm` 3.10.8.

**Comment by reda-alaoui** [comment]
The issue was caused by apache httpd default configuration.

**Comment by cjsfj** [comment]
@reda-alaoui What was the issue with httpd that caused this?

**Comment by reda-alaoui** [comment]
@cjsfj ,

Here is the excerpt of configuration that works for me:

```
       AllowEncodedSlashes NoDecode

        ProxyPreserveHost On
        ProxyPass / http://localhost:8080/ nocanon
        ProxyPassReverse / http://localhost:8080/
```

I hope that helps

**Comment by cjsfj** [comment]
@reda-alaoui ,

Thanks for the quick response. I did not have the AllowEncodedSlashes nor the non canon portion, but even adding those didn't fix my issue.

I'll open an issue in the hopes of getting some help

Thanks,

CJ
