### ISSUE TITLE
Can't install on windows10

### ISSUE THREAD

**Issue by lonyel** [mixu/npm_lazy#72]
Install on Windows10 errors: 
```
D:\nodejs>npm install -g npm_lazy
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm_lazy"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path D:\nodejs\node_global\npm_lazy
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall open

npm ERR! eisdir EISDIR: illegal operation on a directory, open 'D:\nodejs\node_global\npm_lazy'
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\npm-debug.log
```

**Comment by CL0SeY** [comment]
Interesting, I've managed to install on Windows 10 just then myself. (npm 3.5.2 , node 5.10.1)

Is there any reason why your node home directory is d:\nodejs ? 

Mine got put into: 
`C:\Users\Chris\AppData\Roaming\npm\npm_lazy.CMD`

**Comment by langri-sha** [comment]
How did you install Node.js? Could it be you've done it in an elevated prompt and perhaps now you require to run `npm` commands as an administrator?

**Comment by lonyel** [comment]
@CL0SeY The "d:\nodejs" is my npm global install path.
@langri-sha I run npm in Command Prompt Window with Administrator privilege.

**Comment by lonyel** [comment]
I remove the global-path setting in npmrc,then it's OK . Thanks @CL0SeY && @langri-sha .
